### ISSUE TITLE
android:allowBackup="true"

### ISSUE THREAD

**Issue by cdebast** [androidmads/QRGenerator#1]
Hello, 

You're using in your lib: android:allowBackup="true"
This prevents apps using your lib to set it to false. Librry should not set this property. Can you please remove?

**Comment by androidmads** [comment]
I will the library ASAP.

Thanks for your support

**Comment by androidmads** [comment]
I have updated the Library and use `androidmads.library.qrgenearator:QRGenearator:1.0.1`.

Thanks for your support

**Comment by cdebast** [comment]
I see still some -- android:allowBackup="false" -- Can you just ignore all of them?
