### ISSUE TITLE
QR code for Contact

### ISSUE THREAD

**Issue by Special-N9NE** [androidmads/QRGenerator#12]
Hi . how can i encode a Contact ? please help me

**Comment by androidmads** [comment]
Can you please elaborate your requirement for investigating this issue further.

**Comment by JABAJOSHINI** [comment]
how can i add contact after scanning the qr code. I mean contact should be automatically save in the phone book as soon as it is scanned via the qr code. help me to complete

**Comment by VladimirJevtic95** [comment]
> Hi . how can i encode a Contact ? please help me

To encode contact you need to pass the bundle and set the  QRGContents.Type.CONTACT. Also, you need to declare the key values in the bundle to have the same name as the Android ContactsContract class (example - the name is "name", the address is "postal" etc..
