### ISSUE TITLE
JSON in qrCode

### ISSUE THREAD

**Issue by cartantino** [androidmads/QRGenerator#15]
I am having issue passing json as string as inputValue in QR ecoding.
When  I decode it I get apparently random numbers

**Comment by androidmads** [comment]
Can you please share the sample code to investigating this issue further.

**Comment by androidmads** [comment]
This can be implemented like below

`JSONObject jsonBody = new JSONObject();
try {
jsonBody.put("firstName", "Houssem");
jsonBody.put("lastName", "حسام");
} catch (JSONException e) {
e.printStackTrace();
}
qrgEncoder = new QRGEncoder(jsonBody.toString(), null, QRGContents.Type.TEXT, dimen);`
