### ISSUE TITLE
encoding 0, what ever i pass

### ISSUE THREAD

**Issue by Rizwanoranjeclick** [androidmads/QRGenerator#16]
qrgEncoder = new QRGEncoder("test123", null, QRGContents.Type.TEXT, 800);
        qrgEncoder.setColorBlack(Color.GREEN);
        qrgEncoder.setColorWhite(Color.WHITE);
        Log.v("sdasdasdd",""+user_details.account_id);
        try {
            // Getting QR-Code as Bitmap
            bitmap = qrgEncoder.getBitmap();
            // Setting Bitmap to ImageView
            imageView.setImageBitmap(bitmap);
        } catch (Exception e) {
            Toast.makeText(getApplicationContext(),""+e.getMessage(),Toast.LENGTH_LONG).show();
            Log.v("Sadsda",e.getMessage());
        }
    }

**Comment by VladimirJevtic95** [comment]
I tried your code, but instead of a fixed string value I used text from the edit text, and everything works just fine. Try passing the variable. 

Sth like this, it should work just fine
```
String test = editTextTest.getText().toString();
String test = "test123";
QRGEncoder qrgEncoder = new QRGEncoder(test, null, QRGContents.Type.TEXT, 500);
```
