### ISSUE TITLE
QrgSaver().save() not working

### ISSUE THREAD

**Issue by mishraaditya595** [androidmads/QRGenerator#17]
I tried to save the generated QR code to my phone's internal storage but the file is not getting saved.
I am attaching the code used to save below: 
```
QRGSaver().save(folder.path, "$url_et $currentDateTimeString", bitmap, QRGContents.ImageType.IMAGE_PNG)
```

**Comment by isuru18113** [comment]
@mishraaditya595 Did you find a way to save?  did you try to save images for API 29?

**Comment by Zeyu-Li** [comment]
^^ @androidmads

**Comment by androidmads** [comment]
This is due to the changes in the android storage api
