### ISSUE TITLE
Error cannot resolve method

### ISSUE THREAD

**Issue by JamesGBingham** [androidmads/QRGenerator#19]
error: cannot find symbol
                    qrgEncoder.setColorBlack(Color.RED);
                                      ^
  symbol:   method setColorBlack(int)
  location: variable qrgEncoder of type QRGEncoder

error: cannot find symbol
                    qrgEncoder.setColorWhite(Color.Blue);
                                      ^
  symbol:   method setColorWhite(int)
  location: variable qrgEncoder of type QRGEncoder

**Comment by VladimirJevtic95** [comment]
If I understand your question correctly, you are unable to find a variable **qrgEncoder** which you are using to instantiate the main class.

Have you checked the dependencies in the build.gradle file?
```
implementation 'androidmads.library.qrgenearator:QRGenearator:1.0.4'
implementation 'com.google.zxing:core:3.3.2'
```
If this is not the case have you declared the QRGEncoder class correctly in your activity?
```
QRGEncoder qrgEncoder; //or
QRGEncoder qrgEncoder = new QRGEncoder(null, bundle, QRGContents.Type.CONTACT, 500);
```
