### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: com/google/zxing/BarcodeFormat.class

### ISSUE THREAD

**Issue by Johnsonmaung** [androidmads/QRGenerator#2]
In my project, I use
  compile 'com.google.android.gms:play-services-maps:11.0.1'
  compile 'com.google.firebase:firebase-messaging:11.0.1'
  compile 'com.google.firebase:firebase-core:11.0.1'

I got this error when I want to build signed apk!

Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class

**Comment by androidmads** [comment]
It is due to duplicate entry in your dependencies added. you can exclude particular files from dependencies to avoid this error
