### ISSUE TITLE
QR Code storing content in a PDF

### ISSUE THREAD

**Issue by Shabalala9** [androidmads/QRGenerator#23]
I Have tried every method to have the QR Generator generate a QR code, so that when it is decoded the inputted text is stored on a PDF document along with the QR code contents, e.g. QR code type, EC level etc. But I get errors up and down the class. How do I store the inputted text along with the QR code contents on a PDF

**Comment by androidmads** [comment]
Follow the below link will be helpful for you

https://www.geeksforgeeks.org/how-to-generate-a-pdf-file-in-android-app/
