### ISSUE TITLE
Moving the library to a Maven repository

### ISSUE THREAD

**Issue by szymonwrobel** [androidmads/QRGenerator#25]
I get a warning during building my app:
"Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future."
According to this, due to end of service provided by jcenter, can the library be moved to a maven repository?

**Comment by paktiasoftInc** [comment]
Hi, did you found any solution of it? I have same problem

**Comment by szymonwrobel** [comment]
Hello @paktiasoftInc, not really and I don't think there's much we can do. Just wait with hope for the library to be moved. You can copy the code into your project in the worst scenario, but I'd wait with it until there's no other way to use the code.

**Comment by I-sty** [comment]
Is there any update on putting lib in maven?

**Comment by szymonwrobel** [comment]
@I-sty Unfortunately, nothing changed.

**Comment by Diegolotr99** [comment]
Please move it to maven, jcenter is dead

**Comment by szymonwrobel** [comment]
As there is no answer, I've made it myself using [this site](https://jitpack.io/) (lmao it was much easier than I thought).
As there are no tags and releases in this repository, I've created the dependency for the most recent commit (which was a year ago, so it's probably not that bad).
Instead of:
`implementation 'androidmads.library.qrgenearator:QRGenearator:1.0.4'`
You can just use this in your gradle file:
`implementation 'com.github.androidmads:QRGenerator:2ded3dd67f'`

**Comment by szymonwrobel** [comment]
Ok, a quick update.
I returned to the project I was creating and it didn't build with the line I used before, so i changed it to this:
`implementation 'com.github.androidmads:QRGenerator:-SNAPSHOT'`
And it seems to work
