### ISSUE TITLE
Remove border from QR-Code

### ISSUE THREAD

**Issue by mariusgrams** [androidmads/QRGenerator#26]
Hi guys,

I am creating a QR-Code with a text and put it in a imageView. Here is my code:
```
 final String value = "Thats a test value";
 QRGEncoder qrgEncoder = new QRGEncoder(value, null, QRGContents.Type.TEXT, 1024);
 qrgEncoder.setColorBlack(Color.BLACK);
 qrgEncoder.setColorWhite(Color.WHITE);
 final Bitmap bitmap = qrgEncoder.getBitmap();
 ivQrCode.setImageBitmap(bitmap);
 ```

But my generated QR-Code has a border, in my case white. Can I remove this border? 
I have already tried to set the color to transparent but then the ImageView still has exactly the same margin to the sides.
I need to remove the border before generating a bitmap.

See here:
![image](https://user-images.githubusercontent.com/39212237/122640214-89f90100-d0fe-11eb-83a1-2b5cbf523efb.png)

**Comment by szymonwrobel** [comment]
@mariusgrams 
Hello,
yes, there is a way :)
You can use [this function](https://developer.android.com/reference/android/graphics/Bitmap#createBitmap(android.graphics.Bitmap,%20int,%20int,%20int,%20int)): `Bitmap createBitmap (Bitmap source, int x, int y, int width, int height)` to trim your bitmap.

In your case:
`QRGEncoder qrgEncoder = new QRGEncoder(value, null, QRGContents.Type.TEXT, 1024);`
`// setting black color to black and white to white is redundant by the way`
`final Bitmap bitmap = Bitmap.createBitmap(qrgEncoder.getBitmap(), 50, 50, 924, 924);`

Note that for the best results, while using `createBitmap`:
1. x should equal y
2. The width should equal height
3. 2 \* x + width should equal the dimension you used while creating your QR code (in your example it was 1024, so 2 * 50 + 924 = 1024, everything's fine)

Haven't checked it with the values I entered, so you'll have to customize it a little probably. Note that the look also depends on the value you want to change to bitmap, so these values (50, 50, 924, 924) might look good for one thing but will look completely different for some longer strings.

**Comment by GraxCode** [comment]
```java
 private static Bitmap trimLeave5Percent(Bitmap bitmap, int trimColor) {
    int minX = Integer.MAX_VALUE;
    int maxX = 0;
    int minY = Integer.MAX_VALUE;
    int maxY = 0;

    for (int x = 0; x < bitmap.getWidth(); x++) {
      for (int y = 0; y < bitmap.getHeight(); y++) {
        if (bitmap.getPixel(x, y) != trimColor) {
          if (x < minX) {
            minX = x;
          }
          if (x > maxX) {
            maxX = x;
          }
          if (y < minY) {
            minY = y;
          }
          if (y > maxY) {
            maxY = y;
          }
        }
      }
    }
    int xPc = (int) (bitmap.getWidth() * 0.05);
    int yPc = (int) (bitmap.getHeight() * 0.05);

    minX -= xPc;
    minY -= yPc;
    maxX += xPc;
    maxY += yPc;
    return Bitmap.createBitmap(bitmap, Math.max(minX, 0), Math.max(minY, 0),
            Math.min(maxX - minX + 1, bitmap.getWidth()), Math.min(maxY - minY + 1, bitmap.getHeight()));
  }
```
Warning, it's slow.

**Comment by GraxCode** [comment]
Also zxing actually has a setting to set the size of the border when generating the QR code.

**Comment by Acedev003** [comment]
An efficient way would be to implement the in-built solution inside the zxing library.

Use this class :

```
public class NewQRGEncoder extends QRGEncoder
{

   public NewQRGEncoder(String data, Bundle bundle, String type, int dimension)
   {
       super(data,bundle,type,dimension);
   }

   //overriding getBitmap
   public Bitmap getBitmap(int margin) {
        if (!encoded) return null;
        try {
            Map<EncodeHintType, Object> hints = null;
            hints = new EnumMap<>(EncodeHintType.class);
            String encoding = guessAppropriateEncoding(contents);
            if (encoding != null) {
                hints.put(EncodeHintType.CHARACTER_SET, encoding);
            }
            hints.put(EncodeHintType.MARGIN, margin);  
            MultiFormatWriter writer = new MultiFormatWriter();
            BitMatrix result = writer.encode(contents, format, dimension, dimension, hints);
            int width = result.getWidth();
            int height = result.getHeight();
            int[] pixels = new int[width * height];
            for (int y = 0; y < height; y++) {
                int offset = y * width;
                for (int x = 0; x < width; x++) {
                    pixels[offset + x] = result.get(x, y) ? getColorBlack() : getColorWhite();
                }
            }

            Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
            bitmap.setPixels(pixels, 0, width, 0, 0, width, height);
            return bitmap;
        } catch (Exception ex) {
            return null;
        }
    }
}
```
And use the class as:

```
NewQRGEncoder qrgEncoder = new NewQRGEncoder(value, null, QRGContents.Type.TEXT, 1024);

int margin = 1; //Any positive integer
final Bitmap bitmap = Bitmap.createBitmap(qrgEncoder.getBitmap(margin), 50, 50, 924, 924);
```

With margin 0 :

![image](https://user-images.githubusercontent.com/75356264/134634616-c13db7bb-c7f7-477d-9ee7-30c706941706.png)

With margin 2: 

![image](https://user-images.githubusercontent.com/75356264/134635450-0de79414-085e-4129-a038-30f4b25c44dd.png)


Hope this helps 😊

**Comment by androidmads** [comment]
This feature is added in [QR Generator v1.0.1](https://github.com/androidmads/QRGenerator/releases/tag/1.0.1)
