### ISSUE TITLE
Failed to resolve: androidmads.library.qrgenearator:QRGenearator:1.0.4

### ISSUE THREAD

**Issue by acarlstein** [androidmads/QRGenerator#29]
Greetings, 

First, I would like to say thank you for creating this library.

Second, I am getting "Failed to resolve: androidmads.library.qrgenearator:QRGenearator:1.0.4"

It seems that for some reason Gradle cannot find such library. Was it being removed?

**Comment by RubenGarcia** [comment]
I am also affected by this. @acarlstein can you elaborate how you fixed the issue?

**Comment by bilalsaeedjh** [comment]
Help [him]( https://stackoverflow.com/questions/73333677/when-i-implement-third-party-library-in-android-studio-android-studio-show-erro/73343039#73343039)

**Comment by paulos000** [comment]
please help me for this failures

FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find androidmads.library.qrgenerator:QRGenerator:1.0.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidmads/library/qrgenerator/QRGenerator/1.0.3/QRGenerator-1.0.3.pom
       - https://repo.maven.apache.org/maven2/androidmads/library/qrgenerator/QRGenerator/1.0.3/QRGenerator-1.0.3.pom
       - https://jcenter.bintray.com/androidmads/library/qrgenerator/QRGenerator/1.0.3/QRGenerator-1.0.3.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Comment by SamIAmHarris** [comment]
I had to add the maven part in my settings.gradle:

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
