### ISSUE TITLE
Support for NOT jCenter() repository

### ISSUE THREAD

**Issue by damiancioo** [androidmads/QRGenerator#31]
I have following issues:

```
Could not find androidmads.library.qrgenearator:QRGenearator:1.0.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidmads/library/qrgenearator/QRGenearator/1.0.4/QRGenearator-1.0.4.pom
       - https://repo.maven.apache.org/maven2/androidmads/library/qrgenearator/QRGenearator/1.0.4/QRGenearator-1.0.4.pom
       - https://jitpack.io/androidmads/library/qrgenearator/QRGenearator/1.0.4/QRGenearator-1.0.4.pom
 ```

It seems that this is related to lacking of jCenter() alternatives?

**Comment by pramod51** [comment]
yes provide a solution for that

**Comment by Scorpio93** [comment]
Any news?

**Comment by pramod51** [comment]
no

**Comment by jjian322** [comment]
Any updates on this issues? I having the same problem too 😢

**Comment by RubenGarcia** [comment]
I am also affected.

**Comment by RubenGarcia** [comment]
My solution was to copy  QRGContents.java  QRGEncoder.java  QRGSaver.java into my project and change the package name.

**Comment by Volt-AmperAI** [comment]
Hello everyone, is there a solution for this problem? I tried to transfer files QRGContents.java QRGEncoder.java QRGSaver.java did not help.

**Comment by BlairSweigman** [comment]
Same here. works if I keep jCenter()

**Comment by AceAbhishekOfficial** [comment]
Try
maven { url 'https://jcenter.bintray.com/'
        }
It worked

**Comment by kevinsamyn** [comment]
Same issue here. I had have to copy java source files in my project. Thanks @RubenGarcia

**Comment by androidmads** [comment]
We have upgraded the plugin to jitpack

**Comment by arunpk89** [comment]
@androidmads what is the solution? which is the latest update?

**Comment by RupW** [comment]
There's new Gradle dependency settings in the readme to fetch the library from jitpack not jcenter.

**Comment by androidmads** [comment]
Updates in the [readme.md](https://github.com/androidmads/QRGenerator/blob/master/README.md)
