### ISSUE TITLE
Generate mixed language text

### ISSUE THREAD

**Issue by HoussemElBahry** [androidmads/QRGenerator#33]
i wondered how can generate text that contains english and arabic characters as the example below:

JSONObject jsonBody = new JSONObject();
            try {
                jsonBody.put("firstName", "Houssem");
                jsonBody.put("lastName", "حسام");
            } catch (JSONException e) {
                e.printStackTrace();
            }
            qrgEncoder = new QRGEncoder(jsonBody.toString(), null, QRGContents.Type.TEXT, dimen);

**Comment by androidmads** [comment]
The actual json output will be `{"firstName":"Houssem","lastName":"حسام"}` and it is perfectly scanned after QR code generated
