### ISSUE TITLE
What happened to version 1.0.4?

### ISSUE THREAD

**Issue by rtsketo** [androidmads/QRGenerator#36]
Version 1.0.4 existed in jCenter, https://mvnrepository.com/artifact/androidmads.library.qrgenearator/QRGenearator/1.0.4

I have had implemented tests based on this library which now fail, meaning that its functionality has been changed in the current 1.0.1 version on GitHub.

Edit: If someone else is looking for a direct replacement of jCenter's `androidmads.library.qrgenearator:QRGenearator:1.0.4`, Jitpack's `com.github.smartdevelopers-ir:QRGenerator:1.0.4` can be used.

**Comment by androidmads** [comment]
You can use ` implementation 'com.github.androidmads:QRGenerator:1.0.1'` as a direct replacement of jCenter's `androidmads.library.qrgenearator:QRGenearator:1.0.4`
