### ISSUE TITLE
Colors in getBitmap() method

### ISSUE THREAD

**Issue by askarsyzdykov** [androidmads/QRGenerator#38]
Hi, 

in one of [commit](https://github.com/androidmads/QRGenerator/commit/2eef6915d9d6e2ba41d9b8c98035741ecc3f8a96#diff-85b243a24dfacfec59fac80bbc4ea6ffd05d115a6447ed4e19c597273de34a96) you changed colors used in method `getBitmap()`, but in `getBitmap(int margin)` method uses old colors order. 
It broke expected QR displaying in my app, although it is not a problem, because I can inverse colors in the library's client side.
Is it either expected behavior or bug?

<img width="1408" alt="изображение" src="https://github.com/androidmads/QRGenerator/assets/3222305/2c6c53f1-a307-4de2-a39e-e91af5ca9b8b">

**Comment by FlashbakDev** [comment]
Hello, any bugfix scheduled soon ? :'(

**Comment by androidmads** [comment]
I will check

**Comment by androidmads** [comment]
These changes were updated and merged. Reopen if you still facing these issues
