### ISSUE TITLE
Special Charaters are not working in QRcode.

### ISSUE THREAD

**Issue by MOhsain** [androidmads/QRGenerator#39]
I'm making QRcode of this string -> CodeÂ§%1$sÂ§
Everything is perfect but when i scanned that barcode, the charater "Â" is missing from the string.
I thing special charaters are not working in it.
Can you please figure this out. I want to make my app live.
Waiting for your response
Thanks

**Comment by androidmads** [comment]
> 

Yes, will check

**Comment by androidmads** [comment]
This is identified and resolved in version 1.0.2. I am closing this ticket and you can reopen if the persists still.
