### ISSUE TITLE
min api

### ISSUE THREAD

**Issue by nklugman** [androidmads/QRGenerator#4]
Hi,

Does this really need a min API of 15? Is there any way this could be lowered to 14? What is the limiting factor here? 

Thanks!

**Comment by FernandoUFS** [comment]
I have the same problem here. I can't understand why 15.

**Comment by aderoju-adegboyega** [comment]
i've tried a million times now but my app can't even generate a Qr code. How's yours going

**Comment by androidmads** [comment]
Hi,

Minimum API support to 14 is included and closing this issue
