### ISSUE TITLE
importing the library in java file

### ISSUE THREAD

**Issue by Xtrex101** [androidmads/QRGenerator#40]
how do i import the library into the java file before using it

**Comment by AadhilMR** [comment]
Cannot add the implementation in the build.gradle(app module:java). Are there any other dependencies or version compatibilities?

**Comment by gat-hobort** [comment]
same here

**Comment by gat-hobort** [comment]
here is the solution:

Use

implementation 'androidmads.library.qrgenearator:QRGenearator:1.0.3'

in your gradle file

**Comment by AadhilMR** [comment]
@gat-hobort Thanks for the update!

**Comment by gat-hobort** [comment]
next issue I have is that any method of QRGEncoder is private. Dead-end - or do I miss something?

**Comment by psymnx** [comment]
Hey guys I still can't find a way to properly import this...

import com.androidmads.library.qrgenearator.QRGContents
import com.androidmads.library.qrgenearator.QRGEncoder

Throws Unresolved Reference errors

Here's my module level gradle:
implementation ("androidmads.library.qrgenearator:QRGenearator:1.0.3")

And my settings.gradle
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        **maven("https://jitpack.io")**
    }
}

did i put tht maven url in the right place?

**Comment by eleucht1164** [comment]
I was able to import the library using these configurations:

Activity:
```
import androidmads.library.qrgenearator.QRGContents;
import androidmads.library.qrgenearator.QRGEncoder;
```

Module-level build.gradle:
`implementation("com.github.androidmads:QRGenerator:1.0.1")`

settings.gradle:
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
    }
}
```

**Comment by androidmads** [comment]
Hi [eleucht1164](https://github.com/eleucht1164),

Thanks for the steps and this is incorporated in the readme. I am closing this ticket and you can reopen if the persists still.
