### ISSUE TITLE
Why don't we make colours WHITE and BLACK modifiable?

### ISSUE THREAD

**Issue by athanasios-kapelonis** [androidmads/QRGenerator#5]
We can print black and white codes but we can also use other colours,
Now those colours are

`    private static final int WHITE = 0xFFFFFFFF;
    private static final int BLACK = 0xFF000000;`

i don't see any reason why they can't be public non-final

**Comment by androidmads** [comment]
Hi,

Support to change black & white for QR code is included in newer version and closing this issue.
