### ISSUE TITLE
White and Black is flipped

### ISSUE THREAD

**Issue by ronhombre** [androidmads/QRGenerator#55]
This is causing issues with QR Code scanners that can't handle an inverted color for any QR Code.

https://github.com/androidmads/QRGenerator/commit/2eef6915d9d6e2ba41d9b8c98035741ecc3f8a96#diff-85b243a24dfacfec59fac80bbc4ea6ffd05d115a6447ed4e19c597273de34a96

**Comment by androidmads** [comment]
You can pass the colors to the below code to have the inverted QR code:

`qrgEncoder.setColorBlack(Color.parseColor(mColorPreviewBlack.getText().toString()));
qrgEncoder.setColorWhite(Color.parseColor(mColorPreviewWhite.getText().toString()))`

**Comment by ronhombre** [comment]
@androidmads  I have already fixed this on our end. However, you still broke your library so I'm hoping you can fix it

**Comment by androidmads** [comment]
This is identified and resolved in version 1.0.2. I am closing this ticket and you can reopen if the persists still.
