### ISSUE TITLE
Version 1.0.4 has no .aar built file

### ISSUE THREAD

**Issue by phucynwa** [androidmads/QRGenerator#59]
The version 1.0.4 has no aar build file so it cannot be used in our projects. Please fix it.

**Comment by androidmads** [comment]
can you please recheck the readme and download the latest gradle library, try the same.

**Comment by phucynwa** [comment]
@androidmads Please merge my PR. I have self-tested it. You can test it on your side and please release version 1.0.5, many guys need it.
https://github.com/androidmads/QRGenerator/pull/66

**Comment by androidmads** [comment]
@phucynwa changes merged and version 1.0.5 released. Check and let me know for further supports

**Comment by phucynwa** [comment]
@androidmads Thank you. It works fine now.
