### ISSUE TITLE
Cannot resolve symbol 'androidmads'

### ISSUE THREAD

**Issue by MirceaX2Mobile** [androidmads/QRGenerator#61]
Hello. Im trying to add this library to an empty project and is not working.
I was able to use only version 1.0.1
It's the same issue like this one https://stackoverflow.com/questions/72032444/cannot-resolve-symbol-androidmads

I guess the issue is here?
https://github.com/androidmads/QRGenerator/commit/60a215e5257409727d43ea4be2020e395b390ff0#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R27
or here
https://github.com/androidmads/QRGenerator/commit/f7d33bb14bf56073ea44aaf6abee597ce7414d98#diff-494496f5fac3ada65d0053cac146e7b910892317d1dfad3232c32a613b69eab4

**Comment by androidmads** [comment]
can you please recheck the readme and download the latest gradle library, try the same.

**Comment by androidmads** [comment]
Use the library using implementation ‘com.github.androidmads:QRGenerator:1.0.5’.
