### ISSUE TITLE
Update support library to Android X

### ISSUE THREAD

**Issue by arrmixer** [androidmads/QRGenerator#7]
Greetings, currently the project is using an android support library vs AndroidX. I want to make the change and submit a pull request to contribute. 
However, it seems no one is maintaining this project anymore?

Any response from the @androidmads team is welcomed.

Thank you. 

Angel

**Comment by androidmads** [comment]
Hi **Angel**,

We will validate the pull request and merge the changes, keep with us in touch and your contribution mostly welcomed.

Thank you.

Mushtaq
**([Androidmads](http://www.androidmads.info/))**

**Comment by arrmixer** [comment]
Awesome! Thank you. 👍

**Comment by androidmads** [comment]
Hi Angel,

Android X support is included and close this issue. You can re-open this issue for more support for this library.
